Cookies
KaspervanM/WASP pull request #86
Opened 2021-05-25 11:29 UTC by LukeKuijpers

By submitting a PR to this repository, you agree to the terms within the [WASP Code of Conduct](https://github.com/KaspervanM/WASP/blob/master/CODE_OF_CONDUCT.md). Please see the [contributing guidelines](https://github.com/KaspervanM/WASP/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.

### Description

> Describe the purpose of this PR along with any background information and the impacts of the proposed change. For the benefit of the community, please do not assume prior context.
>
> Provide details that support your chosen implementation, including: breaking changes, alternatives considered, changes to the API, etc.
>
> If the UI is being changed, please provide screenshots.

### References

> Include any links supporting this change such as a:
>
> - GitHub Issue/PR number addressed or fixed
> - Auth0 Community post
> - StackOverflow post
> - Support forum thread
> - Related pull requests/issues from other repos
>
> If there are no references, simply delete this section.

### Testing

> Describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.
>
> Please include any manual steps for testing end-to-end or functionality not covered by unit/integration tests.
>
> Also include details of the environment this PR was developed in (language/platform/browser version).

- [ ] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used, if not `master`

2021-05-25 11:47 UTC, KaspervanM commented on client/src/App.vue
> +    toast(toaster, append = false): void {
```suggestion
    toast(toaster: string | undefined, append = false): void {
```

2021-05-25 11:48 UTC, KaspervanM commented on client/src/App.vue
>    data(): { id: string } {
```suggestion
  data(): { id: string; toastCount: number } {

```

2021-05-26 15:58 UTC, evanpacini approved these changes
It works so I approve.

2021-05-27 10:20 UTC, KaspervanM requested changes
It looks good, but reappears every time. Add a cookies system so it only gets shown once.

2021-05-27 10:24 UTC, evanpacini commented
> It looks good, but reappears every time. Add a cookies system so it only gets shown once.

I saw this too, but I don't think a cookie system is required as we are using a router, the page isn't refreshed so it will only reappear when you manually refresh the page (which no one is supposed to be doing in normal use.)

2021-05-31 13:12 UTC, KaspervanM approved these changes

2021-05-31 13:12 UTC, merged